#!/bin/bash
for MDT in `ls /proc/fs/lustre/mdt/`;
do
  if ! grep enabled /proc/fs/lustre/mdt/$MDT/hsm_control > /dev/null; then
    echo CRITICAL - HSM is not enabled on $MDT
    exit 2
  fi

  if [ `wc -l /proc/fs/lustre/mdt/$MDT/hsm/agents | awk '{ print $1 }'`  -eq "0" ] ; then
    echo CRITICAL - No copytool are currently connected
    exit 2
  fi

  if [ `wc -l /proc/fs/lustre/mdt/$MDT/hsm/actions | awk '{ print $1 }'`  -gt "10000" ] ; then
    echo WARNING - More than 10000 items are in the queue
    exit 1
  fi
done

echo OK - HSM is enabled and copytools are connected
exit 0

