#!/bin/bash

# lfs check servers only works as root, not as the NRPE user
lfs_check=$(/usr/bin/sudo /usr/bin/lfs check servers 2>&1 >/dev/null)

if [[ -z $lfs_check ]] ; then
  echo OK - Can reach all the MDTs and OSTs
  exit 0
else
  echo CRITICAL - Could not reach at least one MDT or OST
  echo "$lfs_check"
  exit 2
fi
