#!/bin/bash
if pcs status | grep stonith | grep Started | grep ipmi-poweroff-$(hostname) > /dev/null; then
  echo OK - All stonith device are running
  exit 0
else
  echo CRITICAL - Some stonith devices are stopped
  exit 2
fi
